nelmio_api_doc:
    documentation:
        info:
            title: API REST ful
            description: API REST ful
            version: 1.0.0
    routes: # to filter documented routes
        path_patterns:
            - ^/api(?!/doc$) # Accepts routes under /api except /api/doc
    models: { use_jms: false }
