language: php

php:
  - 7.2

services:
  - mysql

install:
  - composer install
  - cp .env.dist .env
  - cp phpunit.xml.dist phpunit.xml
  
  - mkdir config/jwt
  - openssl genrsa -out config/jwt/private.pem -aes256 4096
  - openssl rsa -pubout -in config/jwt/private.pem -out config/jwt/public.pem

  - php bin/console doctrine:database:create --env=test
  - php bin/console doctrine:schema:create --env=test
  - php bin/console doctrine:schema:update --force --env=test
  - php bin/console doctrine:fixtures:load -n --env=test

script:
  - phpunit